/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data-monitoring/aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_data_monitoring_aggregates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-monitoring/readings/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readings For Current Day */
        get: operations["get_readings_for_current_day_data_monitoring_readings_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-monitoring/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Readings */
        get: operations["get_all_readings_data_monitoring_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DataReading */
        DataReading: {
            /** Id */
            id: number;
            /** Value */
            value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** DataReadingStats */
        DataReadingStats: {
            /** Latest Value */
            latest_value: number | null;
            /** Latest Timestamp */
            latest_timestamp: string | null;
            /** Average Value */
            average_value: number | null;
            /** Min Value */
            min_value: number | null;
            /** Max Value */
            max_value: number | null;
            /** Threshold Exceeded Count */
            threshold_exceeded_count: number;
            /** Total Count */
            total_count: number;
        };
        /** DataReadingWithApiLog */
        DataReadingWithApiLog: {
            /** Id */
            id: number;
            /** Value */
            value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Api Endpoint */
            api_endpoint?: string | null;
            /** Api Status */
            api_status?: number | string | null;
            /** Api Message */
            api_message?: string | null;
            /** Email Sent */
            email_sent: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_stats_data_monitoring_aggregates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReadingStats"];
                };
            };
        };
    };
    get_readings_for_current_day_data_monitoring_readings_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReading"][];
                };
            };
        };
    };
    get_all_readings_data_monitoring_history_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReadingWithApiLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
