"""Data Monitering models

Revision ID: 088fede6cb86
Revises:
Create Date: 2026-01-26 20:36:22.148492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from backend.shared import enums


# revision identifiers, used by Alembic.
revision: str = "088fede6cb86"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_reading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_reading_created_at"), "data_reading", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_data_reading_value"), "data_reading", ["value"], unique=False
    )
    op.create_index(
        "ix_reading_time_value", "data_reading", ["created_at", "value"], unique=False
    )
    op.create_table(
        "data_monitering_api_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_url", sa.String(), nullable=False),
        sa.Column(
            "status_code",
            sqlalchemy_utils.types.choice.ChoiceType(enums.ApiStatusCode),
            nullable=False,
        ),
        sa.Column(
            "message",
            sqlalchemy_utils.types.choice.ChoiceType(enums.ApiStatusMessages),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("data_reading_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_reading_id"],
            ["data_reading.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_monitering_api_log_created_at"),
        "data_monitering_api_log",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_monitering_api_log_data_reading_id"),
        "data_monitering_api_log",
        ["data_reading_id"],
        unique=False,
    )
    op.create_table(
        "email_notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "email_status",
            sqlalchemy_utils.types.choice.ChoiceType(enums.EmailStatus),
            nullable=False,
        ),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("data_reading_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_reading_id"],
            ["data_reading.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_notification_log_data_reading_id"),
        "email_notification_log",
        ["data_reading_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_email_notification_log_data_reading_id"),
        table_name="email_notification_log",
    )
    op.drop_table("email_notification_log")
    op.drop_index(
        op.f("ix_data_monitering_api_log_data_reading_id"),
        table_name="data_monitering_api_log",
    )
    op.drop_index(
        op.f("ix_data_monitering_api_log_created_at"),
        table_name="data_monitering_api_log",
    )
    op.drop_table("data_monitering_api_log")
    op.drop_index("ix_reading_time_value", table_name="data_reading")
    op.drop_index(op.f("ix_data_reading_value"), table_name="data_reading")
    op.drop_index(op.f("ix_data_reading_created_at"), table_name="data_reading")
    op.drop_table("data_reading")
    # ### end Alembic commands ###
